### ISSUE TITLE
[skin] support for 1080XF and Xperience1080

### ISSUE THREAD

**Issue by bromix** [bromix/kodion#44]
Default:
List - ID:50
Thumbnails - ID:500

Video:
List - ID:50
Info list - ID:52
Panel - ID:53
Landscape - ID:54
Poster - ID:55
Thumbnail - ID:500
Banner - ID:60

**Comment by freeman212** [comment]
what are your plans?

**Comment by bromix** [comment]
Support the correct views for each content type the skin supports :)

**Comment by freeman212** [comment]
that's nice :+1: looking forward to this
